feature: ['feature/*', 'feat/*']
story: ['story/*', 'user-story/*', 'improvement/*', 'enhancement/*']
bug: ['bug', 'fix/*', 'bugfix/*']
maintenance: ['maintenance/*', 'refactor/*', 'chore/*']
research: ['research/*']
build: ['build/*', 'release/*']
hotfix: ['hotfix/*']
# documentation: ['docs/*', 'documentation/']
# refactor: refactor/*
# test: ['test/*', 'testing/*']
