on: push

name: Connect Jira

jobs:
  build:
    runs-on: ubuntu-latest
    name: Authenticate with Jira
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

    - name: Jira TODO
      uses: atlassian/gajira-todo@master
      with:
        project: GA
        issuetype: Task
        description: Created automatically via GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
