name: Codeowners Validation

on:
  push:
    branches:
    - staging
    - production
    - main
    
jobs:
  yarn-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: File Existence
      uses: andstor/file-existence-action@v1.0.1
      with:
        files: "package-lock.json"
    - name: Package-lock was found
      if: steps.check_files.outputs.files_exists == 'true'
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('Please remove the package-lock file.  We use yarn on this application.')
