name: Automerge Pull Requests

on:
  # Try merging pull requests belonging to a check suite.
  check_suite:
    types:
      - completed
  # Try merging a pull request when it is approved.
  pull_request_review:
    types:
      - submitted
  # Try merging the specified pull request or all open pull requests if none is specified.
  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Request Automerge Approved
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
          do-not-merge-labels: never-merge
          # required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: false
