name: Development - Pull Requests
on:
  push:
    branches:
      - '!production'

jobs:
  pull_request_drafter:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: 1. Development - Pull Request Drafter
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'staging'
          pr_title: '${{ steps.extract_branch.outputs.branch }}'
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_template: '.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md'
