name: Development Label Pull Request
on:
  - pull_request

jobs:
  pull_request_labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 PR Labeler
        uses: TimonVS/pr-labeler-action@v3.1.0
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
