name: Development Create Pull Request
on:
  push:
    branches:
      - '**'
      - '!staging'
      - '!production'

jobs:
  pull_request_drafter:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 Checkout
        uses: actions/checkout@master

      - name: Step 2 Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Step 3 Pull Request Drafter
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'staging'
          pr_title: "${{ steps.extract_branch.outputs.branch }}" # Title of pull request
          # TODO: Need to action output from release drafter to pr_body
          pr_body: "# Summary<br/>Test Item"              # Full markdown support, requires pr_title to be set
          pr_template: '.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md'   # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          # pr_draft: true                                    # Creates pull request as draft
          pr_allow_empty: true                              # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}
