name: Feature Branch - 1. Create Pull Request
on:
  push:
    branches:
      - '**' # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'staging'
          pr_title: '${{ github.ref }}'
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_template: '.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md'
