name: jira-description-action
on:
  pull_request:
    types: [opened, edited]
jobs:
  add-jira-description:
    runs-on: ubuntu-latest
    steps:
      - uses: cakeinpanic/jira-description-action@v1.2
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_API_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          skip-branches: '^(production|master)$' #optional
          use: 'both' #optional
