name: Production - 3. Version Releaser
on:
  push:
    branches:
      - production
jobs:
  update_release_draft:
    name: Publish release with notes
    runs-on: ubuntu-latest
    # if: "contains(github.event.head_commit.message, 'Prebid Server prepare release ')"
    steps:
      - name: Create and publish release
      - uses: release-drafter/release-drafter@master
        with:
          config-name: .github/release-drafter-config.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
