name: Production - 3. Version Releaser
on:
  push:
    branches:
      - production
jobs:
  create_release:

    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Create and publish release
      - uses: release-drafter/release-drafter@master
        with:
          config-name: .github/release-drafter-config.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
