name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - production
      - staging

  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]

# Setting defaults for security purposes
permissions:
  contents: write
  pull-requests: write

jobs:
  ui-automated-prerelease:
    if: ${{ github.actor != 'dependabot[bot]' && github.ref != 'refs/heads/production' }}
    name: UI Release Drafter and Labeler (Staging)
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
          prerelease: true
          environment: staging
          commitish: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease-identifier: 'rc'

  ui-automated-release:
    if: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/production' }}
    name: UI Release Drafter and Labeler (Production)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
          publish: true
          environment: production
          commitish: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
