on:
  push:
    workflow_dispatch:
      inputs:
      next_version:
        description: 'Release Type'
        required: true
        default: 'minor'
      tags:
        description: 'Test scenario tags'
        # ${{ github.event.inputs.next_version }}
    # Sequence of patterns matched against refs/tags
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"

  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            # Test Release Notes Summary
            _Release Type: ${{ github.event.inputs.next_version }}_
            ## Changes
              - item 1
              - item 2
              - item 3
            draft: true
            prerelease: false
            # repo: Current repository
            # owner: Current owner
