name: Production - 3. Version Releaser
on:
  push:
    branches:
      - production
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Create and Publish Release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
