name: Yarn Validation

on:
  push:
    
jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "package-lock.json"

      - name: FAILURE - Package-lock was found
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Please remove the package-lock file.  We use yarn on this application.')
